//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.lemon.common.utils.excel.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExcelHeadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcelHeadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="excelColList" type="{}ExcelColType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="headRowIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcelHeadType", propOrder = {
    "excelColList"
})
public class ExcelHeadType {

    protected List<ExcelColType> excelColList;
    @XmlAttribute
    protected Integer headRowIndex;

    /**
     * Gets the value of the excelColList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excelColList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcelColList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExcelColType }
     * 
     * 
     */
    public List<ExcelColType> getExcelColList() {
        if (excelColList == null) {
            excelColList = new ArrayList<ExcelColType>();
        }
        return this.excelColList;
    }

    /**
     * Gets the value of the headRowIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeadRowIndex() {
        return headRowIndex;
    }

    /**
     * Sets the value of the headRowIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeadRowIndex(Integer value) {
        this.headRowIndex = value;
    }

}
