//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package com.lemon.common.utils.excel.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.com.gensoft.utils.excel.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExcelTemplateList_QNAME = new QName("", "excelTemplateList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.com.gensoft.utils.excel.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExcelColType }
     * 
     */
    public ExcelColType createExcelColType() {
        return new ExcelColType();
    }

    /**
     * Create an instance of {@link ExcelTemplateType }
     * 
     */
    public ExcelTemplateType createExcelTemplateType() {
        return new ExcelTemplateType();
    }

    /**
     * Create an instance of {@link ExcelTemplateList }
     * 
     */
    public ExcelTemplateList createExcelTemplateList() {
        return new ExcelTemplateList();
    }

    /**
     * Create an instance of {@link ExcelHeadType }
     * 
     */
    public ExcelHeadType createExcelHeadType() {
        return new ExcelHeadType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExcelTemplateList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "excelTemplateList")
    public JAXBElement<ExcelTemplateList> createExcelTemplateList(ExcelTemplateList value) {
        return new JAXBElement<ExcelTemplateList>(_ExcelTemplateList_QNAME, ExcelTemplateList.class, null, value);
    }

}
